create table DR
 (id NUMBER(11) primary key,
 bezeichnung varchar2(255)
);

CREATE TABLE DATAGROUP_X_DR
(
    DATAGROUP_ID INT NOT NULL,
    DR_ID INT NOT NULL,
    CONSTRAINT DATAGROUP_X_DR_DATAGROUP_ID_fk FOREIGN KEY (DATAGROUP_ID) REFERENCES DATAGROUP (ID),
    CONSTRAINT DATAGROUP_X_DR_DR_ID_fk FOREIGN KEY (DR_ID) REFERENCES DR (ID)
);

CREATE TABLE VK
(
    ID integer PRIMARY KEY NOT NULL,
    BEZEICHNUNG VARCHAR2(255)
);

CREATE TABLE DATAGROUP_X_VK
(
    DATAGROUP_ID integer NOT NULL,
    VK_ID integer NOT NULL,
    CONSTRAINT DATAGROUP_X_VK_DATAGROUP_ID_FK FOREIGN KEY (DATAGROUP_ID) REFERENCES DATAGROUP (ID),
    CONSTRAINT DATAGROUP_X_VK_VK_ID_FK FOREIGN KEY (VK_ID) REFERENCES VK (ID)
);